/** @type {import('tailwindcss').Config} */
// Design tokens mapped 1:1 from the Elixir & Stem design reference (Material-style tokens).
module.exports = {
  content: ['./App.tsx', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#061b0e',
        'on-primary': '#ffffff',
        'primary-container': '#1b3022',
        'on-primary-container': '#819986',
        'primary-fixed': '#d0e9d4',
        'primary-fixed-dim': '#b4cdb8',
        secondary: '#4d644b',
        'on-secondary': '#ffffff',
        'secondary-container': '#cfeaca',
        'on-secondary-container': '#536a51',
        tertiary: '#211500',
        'tertiary-container': '#3a2800',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#e9c176',
        'on-tertiary-container': '#b18d48',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f4',
        'on-background': '#1b1c19',
        surface: '#fbf9f4',
        'on-surface': '#1b1c19',
        'surface-variant': '#e4e2dd',
        'on-surface-variant': '#434843',
        'surface-dim': '#dbdad5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        outline: '#737973',
        'outline-variant': '#c3c8c1',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
      },
      borderRadius: {
        DEFAULT: '2px',
        lg: '4px',
        xl: '8px',
        '2xl': '12px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['PlayfairDisplay_600SemiBold'],
        'headline-bold': ['PlayfairDisplay_700Bold'],
        body: ['Inter_400Regular'],
        'body-semibold': ['Inter_600SemiBold'],
      },
    },
  },
  plugins: [],
};
