import type { Merchant, Order, Product, Reward, Review, LoyaltyAccount } from './types';

/**
 * Bundled seed data so the app runs standalone (no backend required).
 * When EXPO_PUBLIC_API_URL is set, api/client.ts fetches from the server instead.
 */
export const mockMerchants: Merchant[] = [
  {
    id: 'm1',
    userId: 'u-m1',
    businessName: 'Elixir & Stem Victoria Island',
    licenseNumber: 'NAFDAC-VR-001234-LIC',
    status: 'approved',
    address: '14 Adeola Odeku St, Victoria Island, Lagos',
    lat: 6.4281,
    lng: 3.4219,
    rating: 4.8,
    deliveryEtaMins: [30, 45],
    distanceKm: 2.5,
  },
  {
    id: 'm2',
    userId: 'u-m2',
    businessName: 'GreenLeaf Abuja',
    licenseNumber: 'NAFDAC-AB-009871-LIC',
    status: 'approved',
    address: '25 Aguiyi-Ironsi St, Maitama, Abuja',
    lat: 9.0579,
    lng: 7.4951,
    rating: 4.6,
    deliveryEtaMins: [40, 60],
    distanceKm: 8.2,
  },
  {
    id: 'm3',
    userId: 'u-m3',
    businessName: 'Herbal Hub Ikeja',
    licenseNumber: 'NAFDAC-IK-0012200-LIC',
    status: 'approved',
    address: '45 Awolowo Rd, Ikeja, Lagos',
    lat: 6.6051,
    lng: 3.3494,
    rating: 4.9,
    deliveryEtaMins: [35, 50],
    distanceKm: 15.3,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    merchantId: 'm1',
    name: 'Blue Dream',
    brand: 'Elixir Reserve',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 24,
    cbdPct: 0.1,
    description:
      'A bright, berry-forward sativa with gentle cerebral lift. A daytime classic from our reserve garden.',
    terpenes: ['Myrcene', 'Pinene', 'Caryophyllene'],
    effects: [
      { icon: 'mood', label: 'Euphoric' },
      { icon: 'spa', label: 'Creative' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4500 },
      { label: '7g', price: 8500 },
      { label: '14g', price: 16000 },
    ],
    stock: 42,
    imageColor: '#cfeaca',
    imageUrl: 'https://images.unsplash.com/photo-1603909223429-69bb7101f420?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 214,
  },
  {
    id: 'p2',
    merchantId: 'm1',
    name: 'Granddaddy Purple',
    brand: 'Elixir Reserve',
    category: 'Flower',
    strainType: 'indica',
    thcPct: 21,
    cbdPct: 0.5,
    description:
      'Deep grape and berry notes with a heavy, settling body feel. Best saved for the end of the day.',
    terpenes: ['Myrcene', 'Linalool', 'Caryophyllene'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5000 },
      { label: '7g', price: 9500 },
      { label: '14g', price: 18000 },
    ],
    stock: 28,
    imageColor: '#e4e2dd',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 167,
  },
  {
    id: 'p3',
    merchantId: 'm1',
    name: 'Lush Orchard',
    brand: 'Orchard Line',
    category: 'Flower',
    strainType: 'indica',
    thcPct: 22,
    cbdPct: 1.2,
    description: 'A sweet, earthy profile with notes of ripe fruit and pine. Perfect for evening relaxation.',
    terpenes: ['Myrcene', 'Limonene', 'Caryophyllene'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'mood', label: 'Euphoric' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4500 },
      { label: '7g', price: 8600 },
      { label: '14g', price: 16200 },
    ],
    stock: 35,
    imageColor: '#d0e9d4',
    imageUrl: 'https://images.unsplash.com/photo-1599839575338-3d8159f4974b?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: 'p4',
    merchantId: 'm1',
    name: 'Wedding Cake',
    brand: 'House Cultivar',
    category: 'Flower',
    strainType: 'hybrid',
    thcPct: 26,
    cbdPct: 0.2,
    description: 'Rich vanilla and pepper over a calm, balanced hybrid base.',
    terpenes: ['Limonene', 'Caryophyllene', 'Linalool'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'mood', label: 'Uplifted' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5500 },
      { label: '7g', price: 10500 },
      { label: '14g', price: 20000 },
    ],
    stock: 19,
    imageColor: '#f0eee9',
    imageUrl: 'https://images.unsplash.com/photo-1601473824699-b077dd2cbb3e?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews: 302,
  },
  {
    id: 'p5',
    merchantId: 'm1',
    name: 'Sour Diesel',
    brand: 'House Cultivar',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 22,
    cbdPct: 0.1,
    description: 'Pungent citrus-fuel sativa with a fast, energizing onset.',
    terpenes: ['Limonene', 'Myrcene', 'Pinene'],
    effects: [
      { icon: 'mood', label: 'Energetic' },
      { icon: 'spa', label: 'Focused' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4000 },
      { label: '7g', price: 7600 },
      { label: '14g', price: 14400 },
    ],
    stock: 51,
    imageColor: '#cfeaca',
    imageUrl: 'https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews: 188,
  },
  {
    id: 'p6',
    merchantId: 'm1',
    name: 'Clarity Drops',
    brand: 'Stem Apothecary',
    category: 'Tinctures',
    thcPct: 2,
    cbdPct: 20,
    description: 'CBD-rich sublingual tincture, 30ml bottle with measured dropper.',
    terpenes: [],
    effects: [{ icon: 'spa', label: 'Calm' }],
    weightOptions: [{ label: '30ml', price: 8500 }],
    stock: 24,
    imageColor: '#ffdea5',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews: 96,
  },
  {
    id: 'p7',
    merchantId: 'm1',
    name: 'Soothe Confections',
    brand: 'Stem Apothecary',
    category: 'Edibles',
    thcPct: 0,
    cbdPct: 0,
    description: '20 pieces, 10mg THC each. Slow-baked fruit confections.',
    terpenes: [],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [{ label: '20 pack', price: 3500 }],
    stock: 60,
    imageColor: '#e9c176',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews: 141,
  },
  {
    id: 'p8',
    merchantId: 'm2',
    name: 'Uplift Reserve',
    brand: 'Verdant',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 23,
    cbdPct: 0.3,
    description: '3.5g organic, sun-grown sativa. Bright citrus and herbs.',
    terpenes: ['Terpinolene', 'Limonene', 'Ocimene'],
    effects: [
      { icon: 'mood', label: 'Uplifted' },
      { icon: 'spa', label: 'Creative' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5500 },
      { label: '7g', price: 10400 },
    ],
    stock: 17,
    imageColor: '#d0e9d4',
    rating: 4.8,
    reviews: 74,
  },
];

export const mockRewards: Reward[] = [
  {
    id: 'free_delivery',
    title: 'Free Delivery',
    subtitle: 'Redeem for 100 pts',
    icon: 'local_shipping',
    points: 100,
  },
  {
    id: '10_off_flower',
    title: '10% Off Flower',
    subtitle: 'Redeem for 150 pts',
    icon: 'local_florist',
    points: 150,
  },
  {
    id: '5_off',
    title: '$5 Off Next Order',
    subtitle: 'Redeem for 200 pts',
    icon: 'savings',
    points: 200,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    productId: 'p1',
    customerId: 'u-c1',
    customerEmail: 'julian@example.com',
    orderItemId: 'oi1',
    rating: 5,
    comment: 'Absolutely love this strain! Perfect for daytime use. The berry notes are incredible.',
    createdAt: '2023-10-26T10:00:00Z',
  },
  {
    id: 'rev2',
    productId: 'p1',
    customerId: 'u-c2',
    customerEmail: 'sarah@example.com',
    orderItemId: 'oi2',
    rating: 4,
    comment: 'Great quality, smooth smoke. Would recommend to anyone looking for a creative boost.',
    createdAt: '2023-10-20T15:30:00Z',
  },
  {
    id: 'rev3',
    productId: 'p3',
    customerId: 'u-c1',
    customerEmail: 'julian@example.com',
    orderItemId: 'oi3',
    rating: 5,
    comment: 'My go-to for evening relaxation. Sweet and earthy, just as described.',
    createdAt: '2023-09-14T09:15:00Z',
  },
  {
    id: 'rev4',
    productId: 'p4',
    customerId: 'u-c3',
    customerEmail: 'mike@example.com',
    orderItemId: 'oi4',
    rating: 5,
    comment: 'The vanilla notes are real! Balanced hybrid that hits just right.',
    createdAt: '2023-10-28T12:00:00Z',
  },
];

export const mockLoyalty: LoyaltyAccount = {
  points: 750,
  tier: 'silver',
  transactions: [
    { id: 'lt1', accountId: 'la1', orderId: 'ES-8842', points: 145, reason: 'order_earned', createdAt: '2023-10-24T14:20:00Z' },
    { id: 'lt2', accountId: 'la1', orderId: 'ES-8710', points: 85, reason: 'order_earned', createdAt: '2023-09-12T19:05:00Z' },
    { id: 'lt3', accountId: 'la1', points: 100, reason: 'signup_bonus', createdAt: '2023-08-01T00:00:00Z' },
    { id: 'lt4', accountId: 'la1', points: -100, reason: 'redeemed_reward', createdAt: '2023-10-01T10:00:00Z' },
  ],
};

export const mockPastOrders: Order[] = [
  {
    id: 'ES-8842',
    customerId: 'u-c1',
    merchantId: 'm1',
    merchantName: 'Elixir & Stem Downtown',
    status: 'delivered',
    paymentMethod: 'pay_on_delivery',
    deliveryAddress: '500 S Grand Ave, Los Angeles, CA',
    items: [
      { id: 'oi1', productId: 'p1', name: 'Blue Dream', weightLabel: '7g', quantity: 1, priceAtPurchase: 8500 },
      { id: 'oi5', productId: 'p7', name: 'Soothe Confections', weightLabel: '20 pack', quantity: 1, priceAtPurchase: 3500 },
    ],
    subtotal: 12000,
    tax: 1140,
    deliveryFee: 500,
    total: 14500,
    createdAt: '2023-10-24T14:20:00Z',
    timeline: [],
  },
  {
    id: 'ES-8710',
    customerId: 'u-c1',
    merchantId: 'm1',
    merchantName: 'Elixir & Stem Downtown',
    status: 'delivered',
    paymentMethod: 'pay_on_delivery',
    deliveryAddress: '500 S Grand Ave, Los Angeles, CA',
    items: [
      { id: 'oi3', productId: 'p3', name: 'Lush Orchard', weightLabel: '3.5g', quantity: 1, priceAtPurchase: 4500 },
      { id: 'oi6', productId: 'p6', name: 'Clarity Drops', weightLabel: '30ml', quantity: 1, priceAtPurchase: 8500 },
    ],
    subtotal: 13000,
    tax: 1235,
    deliveryFee: 0,
    total: 8550,
    createdAt: '2023-09-12T19:05:00Z',
    timeline: [],
  },
];
