import type { Merchant, Order, Product, Reward } from './types';

/**
 * Bundled seed data so the app runs standalone (no backend required).
 * When EXPO_PUBLIC_API_URL is set, api/client.ts fetches from the server instead.
 */
export const mockMerchants: Merchant[] = [
  {
    id: 'm1',
    userId: 'u-m1',
    businessName: 'Elixir & Stem Downtown',
    licenseNumber: 'CA-C10-0001234-LIC',
    status: 'approved',
    address: '412 Olive St, Los Angeles, CA',
    lat: 34.0522,
    lng: -118.2437,
    rating: 4.8,
    deliveryEtaMins: [45, 60],
    distanceMiles: 0.8,
  },
  {
    id: 'm2',
    userId: 'u-m2',
    businessName: 'Verdant Remedies',
    licenseNumber: 'CA-C10-0009871-LIC',
    status: 'approved',
    address: '88 Market St, San Francisco, CA',
    lat: 37.7749,
    lng: -122.4194,
    rating: 4.6,
    deliveryEtaMins: [30, 50],
    distanceMiles: 1.4,
  },
  {
    id: 'm3',
    userId: 'u-m3',
    businessName: 'Golden State Botanics',
    licenseNumber: 'CA-C10-0012200-LIC',
    status: 'approved',
    address: '2215 Telegraph Ave, Oakland, CA',
    lat: 37.8044,
    lng: -122.2712,
    rating: 4.9,
    deliveryEtaMins: [40, 55],
    distanceMiles: 2.1,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    merchantId: 'm1',
    name: 'Blue Dream',
    brand: 'Elixir Reserve',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 24,
    cbdPct: 0.1,
    description:
      'A bright, berry-forward sativa with gentle cerebral lift. A daytime classic from our reserve garden.',
    terpenes: ['Myrcene', 'Pinene', 'Caryophyllene'],
    effects: [
      { icon: 'mood', label: 'Euphoric' },
      { icon: 'spa', label: 'Creative' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4500 },
      { label: '7g', price: 8500 },
      { label: '14g', price: 16000 },
    ],
    stock: 42,
    imageColor: '#cfeaca',
    rating: 4.8,
    reviews: 214,
  },
  {
    id: 'p2',
    merchantId: 'm1',
    name: 'Granddaddy Purple',
    brand: 'Elixir Reserve',
    category: 'Flower',
    strainType: 'indica',
    thcPct: 21,
    cbdPct: 0.5,
    description:
      'Deep grape and berry notes with a heavy, settling body feel. Best saved for the end of the day.',
    terpenes: ['Myrcene', 'Linalool', 'Caryophyllene'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5000 },
      { label: '7g', price: 9500 },
      { label: '14g', price: 18000 },
    ],
    stock: 28,
    imageColor: '#e4e2dd',
    rating: 4.7,
    reviews: 167,
  },
  {
    id: 'p3',
    merchantId: 'm1',
    name: 'Lush Orchard',
    brand: 'Orchard Line',
    category: 'Flower',
    strainType: 'indica',
    thcPct: 22,
    cbdPct: 1.2,
    description:
      'A sweet, earthy profile with notes of ripe fruit and pine. Perfect for evening relaxation.',
    terpenes: ['Myrcene', 'Limonene', 'Caryophyllene'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'mood', label: 'Euphoric' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4500 },
      { label: '7g', price: 8600 },
      { label: '14g', price: 16200 },
    ],
    stock: 35,
    imageColor: '#d0e9d4',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: 'p4',
    merchantId: 'm1',
    name: 'Wedding Cake',
    brand: 'House Cultivar',
    category: 'Flower',
    strainType: 'hybrid',
    thcPct: 26,
    cbdPct: 0.2,
    description: 'Rich vanilla and pepper over a calm, balanced hybrid base.',
    terpenes: ['Limonene', 'Caryophyllene', 'Linalool'],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'mood', label: 'Uplifted' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5500 },
      { label: '7g', price: 10500 },
      { label: '14g', price: 20000 },
    ],
    stock: 19,
    imageColor: '#f0eee9',
    rating: 4.8,
    reviews: 302,
  },
  {
    id: 'p5',
    merchantId: 'm1',
    name: 'Sour Diesel',
    brand: 'House Cultivar',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 22,
    cbdPct: 0.1,
    description: 'Pungent citrus-fuel sativa with a fast, energizing onset.',
    terpenes: ['Limonene', 'Myrcene', 'Pinene'],
    effects: [
      { icon: 'mood', label: 'Energetic' },
      { icon: 'spa', label: 'Focused' },
    ],
    weightOptions: [
      { label: '3.5g', price: 4000 },
      { label: '7g', price: 7600 },
      { label: '14g', price: 14400 },
    ],
    stock: 51,
    imageColor: '#cfeaca',
    rating: 4.6,
    reviews: 188,
  },
  {
    id: 'p6',
    merchantId: 'm1',
    name: 'Clarity Drops',
    brand: 'Stem Apothecary',
    category: 'Tinctures',
    thcPct: 2,
    cbdPct: 20,
    description: 'CBD-rich sublingual tincture, 30ml bottle with measured dropper.',
    terpenes: [],
    effects: [{ icon: 'spa', label: 'Calm' }],
    weightOptions: [{ label: '30ml', price: 8500 }],
    stock: 24,
    imageColor: '#ffdea5',
    rating: 4.9,
    reviews: 96,
  },
  {
    id: 'p7',
    merchantId: 'm1',
    name: 'Soothe Confections',
    brand: 'Stem Apothecary',
    category: 'Edibles',
    thcPct: 0,
    cbdPct: 0,
    description: '20 pieces, 10mg THC each. Slow-baked fruit confections.',
    terpenes: [],
    effects: [
      { icon: 'spa', label: 'Relaxing' },
      { icon: 'bedtime', label: 'Sleepy' },
    ],
    weightOptions: [{ label: '20 pack', price: 3500 }],
    stock: 60,
    imageColor: '#e9c176',
    rating: 4.7,
    reviews: 141,
  },
  {
    id: 'p8',
    merchantId: 'm2',
    name: 'Uplift Reserve',
    brand: 'Verdant',
    category: 'Flower',
    strainType: 'sativa',
    thcPct: 23,
    cbdPct: 0.3,
    description: '3.5g organic, sun-grown sativa. Bright citrus and herbs.',
    terpenes: ['Terpinolene', 'Limonene', 'Ocimene'],
    effects: [
      { icon: 'mood', label: 'Uplifted' },
      { icon: 'spa', label: 'Creative' },
    ],
    weightOptions: [
      { label: '3.5g', price: 5500 },
      { label: '7g', price: 10400 },
    ],
    stock: 17,
    imageColor: '#d0e9d4',
    rating: 4.8,
    reviews: 74,
  },
];

export const mockRewards: Reward[] = [
  {
    id: 'r1',
    title: 'Free Delivery',
    subtitle: 'Redeem for 100 pts',
    icon: 'local_shipping',
    points: 100,
  },
  {
    id: 'r2',
    title: '10% Off Flower',
    subtitle: 'Redeem for 150 pts',
    icon: 'local_florist',
    points: 150,
  },
  {
    id: 'r3',
    title: 'Exclusive Early Access',
    subtitle: 'Connoisseur Perk',
    icon: 'verified',
    points: 0,
  },
];

export const mockPastOrders: Order[] = [
  {
    id: 'ES-8842',
    customerId: 'u-c1',
    merchantId: 'm1',
    merchantName: 'Elixir & Stem Downtown',
    status: 'delivered',
    paymentMethod: 'pay_on_delivery',
    deliveryAddress: '500 S Grand Ave, Los Angeles, CA',
    items: [
      { productId: 'p1', name: 'Blue Dream', weightLabel: '7g', quantity: 1, priceAtPurchase: 8500 },
      { productId: 'p7', name: 'Soothe Confections', weightLabel: '20 pack', quantity: 1, priceAtPurchase: 3500 },
    ],
    subtotal: 12000,
    tax: 1140,
    deliveryFee: 500,
    total: 14500,
    createdAt: '2023-10-24T14:20:00Z',
    timeline: [],
  },
  {
    id: 'ES-8710',
    customerId: 'u-c1',
    merchantId: 'm1',
    merchantName: 'Elixir & Stem Downtown',
    status: 'delivered',
    paymentMethod: 'pay_on_delivery',
    deliveryAddress: '500 S Grand Ave, Los Angeles, CA',
    items: [
      { productId: 'p3', name: 'Lush Orchard', weightLabel: '3.5g', quantity: 1, priceAtPurchase: 4500 },
      { productId: 'p6', name: 'Clarity Drops', weightLabel: '30ml', quantity: 1, priceAtPurchase: 8500 },
    ],
    subtotal: 13000,
    tax: 1235,
    deliveryFee: 0,
    total: 8550,
    createdAt: '2023-09-12T19:05:00Z',
    timeline: [],
  },
];
